apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . }}-config
  labels:
    {{- include "ui.labels" . | nindent 4 }}
data:
 REACT_APP_API_URL: {{ .Values.ui.apiUrl | quote }}


