name: HELM Release and Deploy to EKS 
on:
  pull_request:
    branches:
    - develop
    types: [closed]
  push:
    branches:
    - gh-pages
    tags:
    - '*'

env:
  CLUSTER_NAME: gomydesk
  AWS_REGION: eu-south-1
jobs:
  release:
    if: github.event.pull_request.base.ref == 'develop' && github.event.pull_request.merged == true
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  deployment:
    runs-on: 'ubuntu-latest'
    if: ${{ always() }}
    needs: release
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Check if push is with tag
      run: |
        echo "github.ref: ${{github.ref}}"
        if [[ ${{github.ref}} =~ ^refs/tags/ ]]; then
          echo "Push is with tag"
        else
          echo "Push is not with tag"
        fi
    - name: Deploy to EKS Cluster(Dev)
      if: github.event.pull_request.base.ref == 'develop' && github.event.pull_request.merged == true
      run: |
        echo 'dev'
    - name: Deploy to EKS Cluster(prod)
    #check if push is with tag
      
      if:  github.event_name == 'push' && ${{github.ref}} =~ ^refs/tags/ 
      run: |
        echo 'prod'
      





