name: HELM Release and Deploy to EKS
on:
  pull_request:
    branches:
    - develop
    types: [closed]
  push:
    branches:
    - gh-pages
    tags:
    - '*'

env:
  CLUSTER_NAME: jd
  AWS_REGION: eu-south-1
jobs:
  release:
    if: github.event.pull_request.base.ref == 'develop' && github.event.pull_request.merged == true
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  deployment:
    runs-on: 'ubuntu-latest'
    if: ${{ always() }}
    needs: release
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Set Kube Config
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
        echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
        echo $(cat ~/.kube/config | base64) >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV 
    - name: Check if repo exists
      run: |
        if ! helm repo list | grep -q "ui"; then
          helm repo add ui https://gomydesk.github.io/helmUI/charts
        fi
    - name: Deploy to (Dev)
      if: github.event.pull_request.base.ref == 'develop' && github.event.pull_request.merged == true
      uses: koslib/helm-eks-action@v1.25.2
      env:
        KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
        ENV: ${{ steps.extract_branch.outputs.branch }}
        IMAGE_TAG: ${{ github.sha }}
      with:
        command: helm upgrade --install  gomydesk-ui ui/ui --set env=dev --set ingress.enabled.dev=true 
    - name: Deploy to (Prod)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: koslib/helm-eks-action@v1.25.2
      env:
        KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
        ENV: ${{ steps.extract_branch.outputs.branch }}
        IMAGE_TAG: ${{ github.sha }}
      with:
        command: helm upgrade --install  gomydesk-ui ui/ui --set env=prod   






